FROM rust:1.86 AS builder
ARG TARGETPLATFORM

WORKDIR /tmp/build

COPY . .

RUN apt-get update && apt-get install -y cmake && rm -rf /var/lib/apt/lists/* 
RUN cargo build --release 

FROM debian:12-slim

ARG TARGET
COPY --from=builder /tmp/build/target/*/release/hulygun /usr/local/bin/hulygun
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/bin/hulygun"]
